name: CI
on: push
jobs:
  test_language_features:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip3 install matplotlib numpy
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: npm ci -D
      - run: npm test

      - name: Install Matplotlib from GitHub
        run: |
          pip3 uninstall matplotlib -y
          git clone --depth=1 -b main https://github.com/matplotlib/matplotlib matplotlib-latest
          pip3 install ./matplotlib-latest
      - run: npm test

      - name: Test `npm run build:browser`
        run: npm run build:browser

  test_renderer:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6', '3.10', 'pypy-3.6']
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: "pre-release"
      run: |
        python3 -m pip uninstall -y matplotlib
        python3 -m pip install matplotlib --pre
        ./test/renderer.test.sh
    - name: "stable-release"
      run: |
        python3 -m pip uninstall -y matplotlib
        python3 -m pip install matplotlib
        ./test/renderer.test.sh
