name: CI
on:
  push:
  schedule:
    - cron: 45 9 * * 6  # At 09:45 on Saturday
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Matplotlib from pypi
        run: pip3 install matplotlib numpy
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: npm ci -D
      - run: npm test
      - name: Install Matplotlib from GitHub
        run: |
          pip3 uninstall matplotlib -y
          git clone --depth=1 -b main https://github.com/matplotlib/matplotlib matplotlib-latest
          pip3 install ./matplotlib-latest
      - run: npm test

      - name: Check for updates of Matplotlib
        run: |
          ./scripts/update_matplotlib_source.sh
          python3 ./scripts/dump_color_map.py
          git diff --name-only --exit-code matplotlib color_map.json
