name: CI
on:
  push:
  schedule:
    - cron: 45 9 * * 6  # At 09:45 on Saturday
jobs:
  test_language_features:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Matplotlib from pypi
        run: pip3 install matplotlib numpy
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: npm ci -D
      - run: npm test
      - name: Install Matplotlib from GitHub
        run: |
          pip3 uninstall matplotlib -y
          git clone --depth=1 -b main https://github.com/matplotlib/matplotlib matplotlib-latest
          pip3 install ./matplotlib-latest
      - run: npm test

      - name: Check for updates of Matplotlib
        run: |
          ./scripts/update_matplotlib_source.sh
          python3 ./scripts/dump_color_map.py
          git diff --name-only --exit-code matplotlib color_map.json

      - name: Test webpack build
        run: npm run webpack

  test_example_scripts:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6', '3.10', 'pypy-3.6']
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: "pre-release"
      run: |
        python3 -m pip uninstall -y matplotlib
        python3 -m pip install matplotlib --pre
        ./scripts/test_examples.sh
    - name: "stable-release"
      run: |
        python3 -m pip uninstall -y matplotlib
        python3 -m pip install matplotlib
        ./scripts/test_examples.sh
